"""add_reminder_flags_to_bookings

Revision ID: 3e1071838481
Revises: ea4050d5ff72
Create Date: 2026-03-30 14:01:40.847311

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3e1071838481'
down_revision: str | Sequence[str] | None = 'ea4050d5ff72'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_24h_sent', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('reminder_2h_sent', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('review_sent', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('review_sent')
        batch_op.drop_column('reminder_2h_sent')
        batch_op.drop_column('reminder_24h_sent')

    # ### end Alembic commands ###
